language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
script:
- FROM=${FROM:-mydatakeeper/archlinuxarm:${CARCH}}
- sed -e "s|%FROM%|${FROM}|g" -i 'Dockerfile'
- docker build -t mydatakeeper/drone-makepkg:${CARCH} .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/drone-makepkg:${CARCH}
  on:
    branch: master
env:
  matrix:
  - CARCH=arm
  - CARCH=armv6h
  - CARCH=armv7h
  - CARCH=aarch64
  - CARCH=x86_64 FROM=mydatakeeper/archlinux
  global:
  - secure: FDQ521j6Xa7RaRJktGW4pSVGFbxsi80M8RxcVYSiq+uXr26OBM5fB5CSRIpN/OfZDzqs2QGa/1xx+3dHtH1gNBRcqxv46DJ+0kC4hI1fXwDUCjnJa/0dc9Cp754/9gcsnHTI/swxCRbcYJ52f0Msvl0DeaQlZUfLKCSxJ53cJcHN4CiifulROLE8wtkzNbPQZgGtZOIvJXFtSRGVefUbMkKWz/4Hj5dWTZy4htTBZ8/9naRPuyVwFEoBEHhxp2r/reYwV4gGRXiQLA76nwg2VHrTqwlwhC97s+LSPqKWW0kNKQaTAADYm7duqrZTFmrfMVLC2VsFJ+dqnxPoez+JRNTXZHYRTLUvefsWjLZaqKEi7SSC9Ag5CHWOo2A9tCd+xBnSucXi44FGqiAGo7zMWHfX5FgB+iogvJn31KmhIbvYi1uQIayBPGphcKmr7VOWGMpWXsqe40PTu8cs0A7ujf2q0e//KRnTMvExWg7DCcIzrkv1koUW15j4OAeGQUTVIm9pk7OFF2PjRpvwpxzvyCI0Zi+PMwTbRPHLWkixQFtjD9Vqi+shM18SE2FShUUQBxJavDp1PGxCRz+eDTBBBfhSVWYmA2m2q2cgddbfMf3hn9F0PI/LIOOG2xr7yMbiFkhEaaVFbtcgI3nu0z/+LohCPsTFfGoh93HiXB/Xxm0=
  - secure: P+sFvsVb+72Xo/ROHXde1sUuXg5GbqakLKgz+P9acwmDvYHCk105ro016NE34PTvwKdK8rUAg79SMDcNoirJU/1SBfBagchdwdZdZT06tA5ope9R4vl4on3y/UAwZJ/Y8iHBVTcK2pupxchgSNnMv+J6k1L0B8PR98nwh6ST7CfT1H5s5WY2MjrAtcbGDjpaa83yh+XVFs0BIdc1RgZXILXSXCD7QKo+P8VVn6nAceJXvwoaaFNEtp2bUrwAV6STbM9BUv3+Z5FnzcptfCcMnOB5sNxjaKQc4J8LDTnuPLrG4KBc/iokdZ43LYU1tw5W2YhlIwkGSQv9OEkHFvtNK25HY4sG0IWR9r7D4Ad58R2GzFuSKp6vBPijYw7s5aJbuWblzOmBpsFTdETUDJDGPqb52CpBOW0w6JPJfTV/tv/uh5tDOWGaczyl2A8yBU8gb7fSG4S9xMag56P+kd3833ug3hhcod50w54OnwBPJbqsIxPplcrupziT9k9YiINHdocdP/0c3OvyL0N10E3lR5E1ivwaGLBKjCAlZvID6yAjvtTjps2zhKoFciwhklOESN4vUv+fBz4ysl+ASVhJwEOqfk8Sn9WDUFyh8UHubr6adLFggFSLR2fnsRz0GCKD1W6fBHvPTvGNyAqPP7QxL0h9sWNZ3y8UquV0K5X/YOo=
